# Generated by Django 3.0 on 2021-01-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_recognizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydata',
            name='attendence',
        ),
    ]
