# Generated by Django 3.0 on 2021-01-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_recognizer', '0002_remove_mydata_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mydata',
            name='time',
        ),
        migrations.AddField(
            model_name='mydata',
            name='Date_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
